name = "QuaPy"
uuid = "bf608503-7ba0-4632-bcd4-8c97f8bf3c7a"
authors = ["Mirko Bunse <mirko.bunse@cs.tu-dortmund.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
